### ISSUE TITLE
Model is not sent to layout

### ISSUE THREAD

**Issue by mihaimarin83** [smolyakoff/essential-templating#11]
Hello,
I was trying to use the model in the layout but I saw that it's not possible. Could you please add in Essential.Templating.Razor.Template and overload for ResolveLayout like this:
protected ITemplate ResolveLayout(string name, object model, Dictionary<string, object> contextEnvironment)
    {
      if (string.IsNullOrEmpty(name))
        return (ITemplate) null;
      Template template = this._templateContext.Resolve(name, model, this.Culture, (IDictionary<string, object>) contextEnvironment);
      if (template == null)
        throw new InvalidOperationException("Layout template was not found.");
      else
        return (ITemplate) template;
    }

And, in TemplateContext an overload for Resolve with model.

Do you see any this wrong with that?

Best regards,
Mihai M

**Comment by smolyakoff** [comment]
Should be fixed in Essential.Templating.Razor version 1.0.8
