### ISSUE TITLE
Incompatible with RazorEngine 3.5.2

### ISSUE THREAD

**Issue by andydoyle** [smolyakoff/essential-templating#7]
After updating RazorEngine from 3.4.1 to 3.5.2, Essential Templating throws an exception when trying to render an e-mail using 

The top of the stack trace is:

System.MissingMethodException: Method not found: 'System.String RazorEngine.Templating.ITemplate.Run(RazorEngine.Templating.ExecuteContext)'.
   at Essential.Templating.Razor.Email.TemplateEngineExtensions.RenderEmail(ITemplateEngine templateEngine, String path, Object viewBag, CultureInfo culture)

We've reverted RazorEngine back to 3.4.1 and the issue no longer exists.

**Comment by smolyakoff** [comment]
RazorEngine developers changed their API significantly when moved from 3.4 to 3.5. I will need some time to review them and adjust my code.

**Comment by smolyakoff** [comment]
I've added support for RazorEngine 3.5.3 and updated nuget packages. But many methods I use were marked as obsolete in RazorEngine 3.5.x. Will think how to switch to the newer API.

By the way you can consider using bare RazorEngine as it now have many features such as template caching and template resolution built-in.
