### ISSUE TITLE
After upgrade - error started occuring?

### ISSUE THREAD

**Issue by dandcg** [smolyakoff/essential-templating#8]
Hi,

After nuget upgrade to - any ideas....

  ----> Essential.Templating.Common.TemplateEngineException : This kind of usage is no longer supported!
  ----> System.NotSupportedException : This kind of usage is no longer supported!

**Comment by smolyakoff** [comment]
This happens with RazorEngine 3.6.0. You can downgrade RazorEngine package to 3.5.3 if you still want to use Essential Templating wrappers.

**Comment by smolyakoff** [comment]
This should work fine with version 1.0.7 of Essential.Templating.Razor
