### ISSUE TITLE
Issue with Using Razor.Email.EmailTemplate

### ISSUE THREAD

**Issue by MX-Boyan** [smolyakoff/essential-templating#9]
I get the following error when trying to use either a VB or C# template from within my VB.NET project.

Essential.Templating.Razor.Runtime.TypeMismatchException: Expected base template type: RazorEngine.Templating.ITemplate`1[VB$AnonymousType_0`2[System.String,System.String]]. Actual base template type: Essential.Templating.Razor.Email.EmailTemplate

**Comment by smolyakoff** [comment]
Could you, please, provide the details of the template you are using? If your are using typed template then the following declaration should be included in the top of the template:

@inherits Essential.Templating.Razor.Email.EmailTemplate<ModelType>

**Comment by MX-Boyan** [comment]
I am going to close this issue. It was an issue with proper usage. I like what you've done with this, great job!

If I can only make one suggestion: the lack of documentation makes it hard to use. I had to get the source and look at your tests to figure out how to properly use it.
